FROM intel/oneapi-runtime:2025.3.1-0-devel-ubuntu24.04
ARG PIP_OPTS=""
ENV PIP_OPTS=$PIP_OPTS
RUN apt-get -y update && apt-get install -y python3 python-dev-is-python3 && apt-get -y install python$(python -V|grep -Eo '\b[0-9]+\.[0-9]+')-dev python3-pip
RUN pip install $PIP_OPTS --break-system-packages torch torchvision torchaudio --index-url http://download.pytorch.org/whl/xpu --trusted-host download.pytorch.org
