FROM nvcr.io/nvidia/l4t-jetpack:r36.4.0
COPY requirements.txt test-requirements.txt /root
ARG PIP_OPTS=""
ENV PIP_OPTS=$PIP_OPTS
RUN apt-get -yq update && apt-get install -yq python3-pip
RUN pip install $PIP_OPTS --index-url=https://pypi.jetson-ai-lab.io/jp6/cu126 torch torchao
RUN pip install $PIP_OPTS -r /root/jetson-requirements.txt -r /root/test-requirements.txt
WORKDIR /
ENV PYTHONPATH=/
COPY preframr /preframr
COPY tests /tests
COPY run_tests.sh .
RUN ./run_tests.sh
